# This is workflow runs on PR
#
name: Check Pull Request

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: PR_${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: '▶️ actions'
    uses: ./.github/workflows/dependencies.yml

  pr-lint:
    name: '▶️ actions'
    uses: ./.github/workflows/pr-lint.yml

  npm-lint:
    name: '▶️ actions'
    needs: [pr-lint]
    uses: ./.github/workflows/npm-lint.yml

  npm-test:
    name: '▶️ actions'
    needs: [npm-lint]
    uses: ./.github/workflows/npm-test.yml

  codeql:
    name: '▶️ actions'
    needs: [npm-lint]
    uses: ./.github/workflows/codeql.yml
